src/Wanawork/UserBundle/Entity/CVFile.php
<?php
namespace Wanawork\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Wanawork\UserBundle\Interfaces\EntityWithFileInterface;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * CV In form a of file
 * @author Ilya Biryukov <ilya@wanawork.ie>
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @Assert\GroupSequence({"CVFile", "step1"})
 * @Assert\Callback(methods={"validateFile"}, groups={"Default", "step1"})
 */
class CVFile extends CV implements EntityWithFileInterface
{
    /**
     * The actual cv document
     * @var \Symfony\Component\HttpFoundation\File\File | null
     * 
     * @Assert\File(maxSize="1M", mimeTypes = 
     *  {"application/pdf", "application/x-pdf", "application/msword", 
     *      "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.oasis.opendocument.text"},
     *  mimeTypesMessage="CV File format is invalid. Please upload PDF, open office or a word document",
     *  groups={"Default", "step1"}
     * )
     * 
     */
    protected $file;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $filePath;
    
    public function validateFile(ExecutionContextInterface $context)
    {
        // this is done for cases when the form is resubmitted and the file is empty
        if ($this->file === null && $this->filePath === null) {
            $context->addViolationAt('file', 'Please upload a CV');
        }
    }
    
    /**
     * 
     * @return \Symfony\Component\HttpFoundation\File
     */
    public function getFile()
    {
        if(!$this->file instanceof \SplFileInfo && file_exists($this->getAbsolutePath())) {
            $this->file = new File($this->getAbsolutePath(), $checkPath = false);
        }
        return $this->file;
    }
    
    public function setFile(File $file)
    {
        $this->file = $file;
        $this->preUpload();
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->file) {
            // do whatever you want to generate a unique name
            $this->filePath = sha1(uniqid(mt_rand(), true)) . '.'
                . $this->file->guessExtension();
        }
    }
    
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }
    
        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->file->move($this->getUploadRootDir(), $this->filePath);
        unset($this->file);
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $file = $this->getAbsolutePath();
        if ($file) {
            unlink($file);
        }
    }
    
    public function getAbsolutePath()
    {
        return null === $this->filePath ? null
        : $this->getUploadRootDir() . '/' . $this->filePath;
    }
    
    public function getWebPath()
    {
        return null === $this->filePath ? null
        : $this->getUploadDir() . '/' . $this->filePath;
    }
    
    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded documents should be saved
        return (__DIR__ . '/../../../../web/' . $this->getUploadDir());
    }
    
    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw when displaying uploaded
        // doc/image in the view.
        return 'uploads/cvs';
    }
    
    public function getType()
    {
        return self::TYPE_FILE;
    }
    
    /**
     * Generate a name for this pdf
     * @return string
     */
    public function getFileName()
    {
        $name = trim($this->getProfile()->getName());
        $name = preg_replace('/\s+/', '_', $name);
        $name = preg_replace('/[^a-zA-Z0-9_]/', '', $name);
        if (!strlen($name)) {
            $name = $this->getProfile()->getId();
        }
        
        $name .= '_' . $this->getId();
        $name .= '.' . $this->getFile()->guessExtension();
        
        return $name;
    }
}

src/Wanawork/UserBundle/Form/EmployerProfileType.php
<?php

namespace Wanawork\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Wanawork\UserBundle\Repository\SectorRepository;
use Wanawork\UserBundle\Repository\SectorJobRepository;

class EmployerProfileType extends AbstractType
{
	
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('companyName', null, array('label' => 'Company Name'))
            ->add('companyNumber', "text", array('label' => 'CRO Number', 'required' => false))
            ->add('contactName', null, array('label' => 'Contact name'))
            
            ->add('industries',  null, array('label' => 'Industries, where your company operates',
                'query_builder' => function(SectorRepository $rep) {
                    return $rep->createQueryBuilder('industry')->orderBy('industry.name', 'ASC');
                },
            ))
                
            ->add('professions', null, array('label' => 'Professions, you are looking for hire',
                'query_builder' => function(SectorJobRepository $er){
                    return $er->createQueryBuilder('profession')->addOrderBy('profession.name', 'ASC');
                },
            ))

            ->add('email')
            ->add('website')
            ->add('facebook')
            ->add('twitter')
            ->add('linkedin')
            ->add('skype')
            ->add('about', null, array('label' => 'Company Description'))
            //->add('isVerified')
        
            ->add('phoneNumber', null, array('label' => 'Phone Number'))
            ->add('address')
            ->add('city')
            //->add('verifiedBy')
            ->add('county', null, array('empty_value' => 'Please select'))
            ->add('avatarFile', null, array(
            		'label' => 'Company Logo'
            ));
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Wanawork\UserBundle\Entity\EmployerProfile'
        ));
    }

    public function getName()
    {
        return 'wanawork_userbundle_employerprofiletype';
    }
}

src/Wanawork/UserBundle/Controller/EmployerProfileController.php
<?php
namespace Wanawork\UserBundle\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Wanawork\UserBundle\Entity\User;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Wanawork\UserBundle\Entity\EmployerProfile;
use Wanawork\UserBundle\Form\EmployerProfileType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Wanawork\UserBundle\Entity\Billing\VerificationOrder;

/**
 * EmployerProfile controller.
 *
 * @Route("/company")
 */
class EmployerProfileController extends Controller
{
    /**
     * Lists all EmployerProfile entities.
     *
     * @Route("/", name="company")
     * @Template()
     * @Secure(roles="ROLE_ADMIN")
     */
    public function indexAction()
    {
        $dql = "SELECT employer FROM WanaworkUserBundle:EmployerProfile employer ORDER BY employer.id DESC";
        
        $query = $this->getDoctrine()->getManager()->createQuery($dql);
        
        $perPage = 10;
        $pageNumber = $this->get('request')->query->get('page', 1);
        
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate($query, $pageNumber, $perPage);
        
        
        return array(
            'employers' => $pagination,
        );
    }

    /**
     * Displays a form to create a new EmployerProfile entity.
     *
     * @Route("/new", name="company_new")
     * @Template()
     * @Secure(roles="ROLE_USER")
     */
    public function newAction()
    {
        $user = $this->getUser();
		
        $employerProfile = new EmployerProfile();
        $employerProfile->setContactName($user->getName());
        $employerProfile->addUser($user, $isAdmin = true);
        $form  = $this->createForm(new EmployerProfileType(), $employerProfile);
        
        if ($this->getRequest()->isMethod('POST')) {
            $form->bind($this->getRequest());
            
            if ($form->isValid()) {
                $employerService = $this->get('wanawork.employer_service');
                $employerService->createProfile($employerProfile, $user);
                return $this->redirect($this->generateUrl('company_show', array('slug' => $employerProfile->getSlug())));
            }
        }

        return array(
        	'user' => $user,
            'employerProfile' => $employerProfile,
            'form'   => $form->createView(),
        );
    }

//     public function createAction($id, Request $request)
//     {
//     	$user = $this->getDoctrine()->getRepository('WanaworkUserBundle:User')->find($id);
//     	if(!$user instanceof User) {
//     		throw $this->createNotFoundException("Account is not found");
//     	}
    	
//     	$security = $this->get('security.context');
//     	if(!$security->isGranted('EDIT', $user)) {
//     		throw new AccessDeniedException("You don't have permission this access this page");
//     	}
    	
//         $entity  = new EmployerProfile();
//         $form = $this->createForm(new EmployerProfileType(), $entity);
//         $form->bind($request);

//         if ($form->isValid()) {
// 			$employerService = $this->get('wanawork.employer_service');
// 			$employerService->createProfile($entity, $user);
			
// 			$this->get('session')->getFlashBag()->add('messages', 'Profile Saved');
			
//             return $this->redirect($this->generateUrl('company_show', array('id' => $user->getId())));
//         }

//         return array(
//         	'user' => $user,
//             'entity' => $entity,
//             'form'   => $form->createView(),
//         );
//     }

    /**
     * Displays a form to edit an existing EmployerProfile entity.
     *
     * @Route("/{slug}/edit", name="company_edit")
     * @Template()
     * @Secure(roles="ROLE_EMPLOYER")
     * @ParamConverter("profile", class="WanaworkUserBundle:EmployerProfile", options={"mapping": {"slug":"slug"}})
     */
    public function editAction(EmployerProfile $profile)
    {
        $em = $this->getDoctrine()->getManager();

        $security = $this->get('security.context');
        if(!$security->isGranted('EDIT', $profile)) {
        	throw new AccessDeniedException("You don't have permission to access this page");
        }

        $editForm = $this->createForm(new EmployerProfileType(), $profile);
        
        if($this->getRequest()->isMethod('POST')) {
            $editForm->bind($this->getRequest());
            
            if ($editForm->isValid()) {
                $em->flush();
                return $this->redirect($this->generateUrl('company_show', array('slug' => $profile->getSlug())));
            }
        }
        
        return array(
            'profile'      => $profile,
            'form'   => $editForm->createView(),
        );
    }
    
    /**
     * Submit request to be verified
     * @param EmployerProfile $profile
     * @Route("/{slug}/verification-request", name="employer_verification_request")
     * @Template()
     * @Method({"GET", "POST"})
     * @Secure(roles="ROLE_USER")
     */
    public function verificationAction(EmployerProfile $profile)
    {
        $security = $this->get('security.context');
        if (!$security->isGranted("EDIT", $profile)) {
            throw new AccessDeniedException();
        }
        
        if($profile->isVerified()) {
            return $this->redirect($this->generateUrl('my_employer_profile'));
        }
        
        if ($profile->isVerificationPaid()) {
            return $this->redirect($this->generateUrl('employer_verification_request_pending', array(
            	'slug' => $profile->getSlug(),
            )));
        }
        
        return array(
        	'profile' => $profile,
        );
    }
    
    /**
     * @Route("/{slug}/verification-request", name="employer_verification_request_pending")
     * @Template()
     */
    public function verificationPendingAction(EmployerProfile $profile)
    {
        return array();
    }

//     /**
//      * Deletes a EmployerProfile entity.
//      *
//      * @Route("/{id}/delete", name="company_delete")
//      * @Method("POST")
//      * @Secure(roles="ROLE_ADMIN")
//      */
//     public function deleteAction(Request $request, $id)
//     {
//         $form = $this->createDeleteForm($id);
//         $form->bind($request);

//         if ($form->isValid()) {
//             $em = $this->getDoctrine()->getManager();
//             $entity = $em->getRepository('WanaworkUserBundle:EmployerProfile')->find($id);

//             if (!$entity) {
//                 throw $this->createNotFoundException('Unable to find EmployerProfile entity.');
//             }

//             $em->remove($entity);
//             $em->flush();
//         }

//         return $this->redirect($this->generateUrl('company'));
//     }

//     private function createDeleteForm($id)
//     {
//         return $this->createFormBuilder(array('id' => $id))
//             ->add('id', 'hidden')
//             ->getForm()
//         ;
//     }
    
//     public function profileStepAction(User $user) {
//     	$security = $this->get('security.context');
//     	$em = $this->getDoctrine()->getManager();
    	
//     	if((!$employerProfile && !$security->isGranted('EDIT', $user)) || 
//     		($employerProfile && !$security->isGranted('EDIT', $employerProfile))) {
//     		throw new AccessDeniedException('You do not have permission to access this page');
//     	}
    	
//     	if(!$employerProfile) {
//     		$employerProfile = new EmployerProfile();
//     		$employerProfile->setEmail($user->getEmail());
//     	}
    	
//     	$form = $this->createForm(new EmployerProfileType(), $employerProfile);
//     	$request = $this->getRequest();
//     	if($request->isMethod('POST')) {
//     		$form->bind($request);
//     		if($form->isValid()) {
    			
    			
//     			if(!$user->getEmployerProfile()) {
//     				$employerService = $this->get('wanawork.employer_service');
//     				$employerService->createProfile($form->getData(), $user);
//     			} else {
//     				$user->setEmployerProfile($employerProfile);
//     				$em->persist($employerProfile);
//     				$em->flush();
//     			}
//     			return $this->redirect($this->generateUrl('employer_profile_saved'));
//     		}
//     	}
    	
//     	return array(
//     		'form' => $form->createView(),
//     		'user' => $user,
//     		'path' => $this->generateUrl('employer_step2', array('id' => $user->getId()))
//     	);
//     }
    
//     /**
//      * @Route("/profile-saved", name="employer_profile_saved")
//      * @Template()
//      */
//     public function profileSavedStepAction() {
//     	return array(
    			
//     	);
//     }
    
    /**
     * @Route("/{slug}/mark-verified", name="company_mark_verified")
     * @Method("POST")
     * @Secure(roles="ROLE_ADMIN")
     */
    public function markVerifiedAction(EmployerProfile $profile)
    {
        $profile->setIsVerified(true);
        $profile->setVerifiedBy($this->getUser());
        $this->getDoctrine()->getManager()->flush();
        
        return $this->redirect($this->generateUrl('company'));
    }
    
    /**
     * @Route("/{slug}/revoke-verification", name="company_mark_unverified")
     * @Method("POST")
     * @Secure(roles="ROLE_ADMIN")
     */
    public function revokeVerificationAction(EmployerProfile $profile)
    {
        $profile->setIsVerified(false);
        $profile->setVerifiedBy(null);
        $this->getDoctrine()->getManager()->flush();
    
        return $this->redirect($this->generateUrl('company'));
    }
    
    /**
     * Finds and displays a EmployerProfile entity.
     *
     * @Route("/{slug}", name="company_show")

src/Wanawork/UserBundle/Resources/views/EmployerProfile/_form.html.twig
{{ form_errors(form) }}
<form action="" method="post" {{ form_enctype(form) }} novalidate class="form-horizontal">
    
    <fieldset>
    	<legend>Company Information</legend>
    	
    	{{ form_row(form.companyName) }}
    	{{ form_row(form.companyNumber) }}
    	{{ form_row(form.address) }}
    	{{ form_row(form.city) }}
    	{{ form_row(form.county) }}
    	{{ form_row(form.phoneNumber) }}
    	{{ form_row(form.email) }}
    	{{ form_row(form.website) }}
    	{{ form_row(form.skype) }}
    </fieldset>
    
    <fieldset>
    	<legend>Company Contact</legend>
    	{{ form_row(form.contactName) }}
    </fieldset>
    
    <fieldset>
    	<legend>Social Networks</legend>
    	
    	<div class="control-group">
            {{ form_label(form.facebook) }}
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on">facebook.com/</span>
                    {{ form_widget(form.facebook,  {attr: {placeholder: 'Username'}}) }}
                </div>
	    	    {{ form_errors(form.facebook) }}
	        </div>
	    </div>
	    
    	
    	<div class="control-group">
            {{ form_label(form.twitter) }}
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on">@</span>
                    {{ form_widget(form.twitter,  {attr: {placeholder: 'Username'}}) }}
                </div>
	    	    {{ form_errors(form.twitter) }}
	        </div>
	    </div>
    
    	{{ form_row(form.linkedin) }}
    	
    </fieldset>
    
    <fieldset>
    	<legend>Other Information</legend>
    	{{ form_rest(form) }}
    </fieldset>
    
    <div class="control-group">
		<div class="controls">
			<button type="submit" class="btn btn-main ">Save</button>
		</div>
	</div>
</form>

src/Wanawork/UserBundle/Resources/views/EmployerProfile/edit.html.twig
{% extends app.request.isXmlHttpRequest ? "::blank.html.twig" : "WanaworkUserBundle::base.html.twig" %}

{% block title %}Edit Company Profile{% endblock %}

{% block body %}

<div class="row">
    <div class="span12 heading">
        <h1>Edit Company Profile</h1>
    </div>
</div>

<div class="row">
	<div class="span12">
	    <div style="background:#fff; padding: 5px 20px;">
		{% include 'WanaworkUserBundle:EmployerProfile:_form.html.twig' %}
		</div>
	</div>
</div>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
{% stylesheets filter='?yui_css' filter='cssrewrite'
	'@WanaworkUserBundle/Resources/public/css/employerProfile/form.css'%}
	<link rel="stylesheet" type="text/css" media="all" href="{{ asset(asset_url) }}" />
{% endstylesheets %}		
{% endblock %}

{% block javascripts %}
{{ parent() }}
{% javascripts filter='?yui_js' 
	'@WanaworkUserBundle/Resources/public/js/employer/form.js'%}
	<script src="{{ asset(asset_url) }}"></script>
{% endjavascripts %}
{% endblock %}

src/Wanawork/UserBundle/Resources/views/EmployerProfile/index.html.twig
{% extends "WanaworkUserBundle::base.html.twig" %}
{% block title %}
Admin Panel - Employers
{% endblock %}

{% block body %}
{% include 'WanaworkUserBundle:User:_admin-panel.html.twig' with {menu_selection: 'company'} %}

<table class="default-table">
    <thead>
        <tr>
            <th>Company name</th>
            <th>Contact name</th>
            <th>Email</th>
            <th>Is verified</th>
            <th>Phone Number</th>
            <th>City</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for employer in employers %}
        <tr>
            <td><a href="{{ path('company_show', {slug: employer.slug }) }}">{{ employer.companyName }}</a></td>
            <td>{{ employer.contactName }}</td>
            <td>{{ employer.email }}</td>
            <td>
                {{ employer.isVerified ? 'Yes' : "No" }}
                {% if employer.isVerified %}
                <br />
                By {{ employer.verifiedBy.name }}
                {% endif %}
            </td>
            <td>{{ employer.phoneNumber }}</td>
            <td>{{ employer.city }}</td>
            <td>
            
                <div class="btn-group">
				  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
				    Action
				    <span class="caret"></span>
				  </a>
				  <ul class="dropdown-menu">
				    <li>
                        <a href="{{ path('company_show', {slug: employer.slug}) }}">Show</a>
                    </li>
                    <li>
                        <a href="{{ path('company_edit', {slug: employer.slug }) }}">Edit</a>
                    </li>
                    <li>
                        {% if employer.isVerified %}
                        <a class="verification-link" href="{{ path('company_mark_unverified', {slug: employer.slug}) }}">Revoke Verification</a>
                        <form style="display:none;" method="post" action="{{ path('company_mark_unverified', {slug: employer.slug}) }}">
                        </form>
                        {% else %}
                        <a class="verification-link" href="{{ path('company_mark_verified', {slug: employer.slug}) }}">Grant Verification</a>
                        <form style="display:none;" method="post" action="{{ path('company_mark_verified', {slug: employer.slug}) }}">
                        </form>
                        {% endif %}
                    </li>
				  </ul>
				</div>
                </ul>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="row">
	<div class="span12">
		<div class="navigation">
    	{{ knp_pagination_render(employers) }}
		</div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
	{{ parent() }}
	
	{% javascripts filter='?yui_js' 
	'bundles/wanaworkuser/js/employer/index.js'
	 %}
		<script src="{{ asset(asset_url) }}"></script>
	{% endjavascripts %}
{% endblock %}

src/Wanawork/UserBundle/Resources/views/EmployerProfile/show.html.twig
{% extends "WanaworkUserBundle::base.html.twig" %}

{% block title %}{{ profile.companyName }} - Company Profile{% endblock %}
{% block meta %}
<meta content="Company profile for {{ profile.companyName }}" name="description" />
{% endblock %}

{% block body %}
<div class="row">
    <div class="span12">
        <div class="profile">
            
            {% if profile.isVerified %}
            <span class="verification-label label label-success">Company Verified</span>
            {% else %}
            <a href="{{ path('employer_verification_request', {slug: profile.slug}) }}" 
              title="The identity of this company has not been yet verified"><span class="verification-label label label-warning">Company Not Verified</span></a>
            {% endif %}
        
            <section class="top clearfix">
            
                <div class="column column1">
                    <div class="avatar">
		                {% if profile and profile.webPath %}
					    <img src="{{ asset((profile.webPath) | apply_filter('thumbnail_145_wide'))  }}" id="profileImg" />
						{% else %}
						<img src="{{ asset('images/avaPlaceHold.jpg') }}" id="profileImg" />
						{% endif %}
					</div>
                </div>
                
                <div class="column column2">
	                <h1 class="company-name"> 
						{{ profile.companyName }}
					</h1>
					
					<div class="two-line-pair company-number">
					   <div class="heading">Company Number</div>
					   <div class="text">{{ profile.companyNumber ? profile.companyNumber : 'Not provided' }}</div>
					</div>
					
					<div class="two-line-pair company-contact">
					   <div class="heading">Contact Name</div>
					   <div class="text">{{ profile.contactName }}</div>
					</div>
					
                </div>
                
                <div class="column column3">
                
                    <h3>Company Description</h3>
                    {% if profile.about %}
                        {{ profile.about }}
                    {% else %}
                        Not provided
                    {% endif %}
                </div>
            
            </section>
            
            <section class="middle clearfix">
                
                {% if profile.website %}
                <div class="with-icon contact-details">
                    <img src="{{ asset('static/typicons.2.0/png-24px/world.png') }}" />
                    <a href="{{ profile.website }}">{{ profile.website }}</a>
                </div>
                {% endif %}
                
                {% if is_granted('VIEW', profile) %}
                <div class="with-icon contact-details">
                    <img src="{{ asset('static/typicons.2.0/png-24px/mail.png') }}" />
                    <a href="mailto:{{ profile.email }}">{{ profile.email }}</a>
                </div>
                
                <div class="with-icon contact-details">
                    <img src="{{ asset('static/typicons.2.0/png-24px/device-phone.png') }}" />
                    <tel>{{ profile.phoneNumber }}</tel>
                </div>
                {% endif %}
            
            </section>
            
            <section class="bottom clearfix">
            
                <div class="column column1">
                    <h3>Company Address</h3>
                    {{ profile.address }}<br/>
				    {{ profile.city }}<br/>
				    {{ profile.county }}
                </div>
                
                <div class="column column2">
                    <h3>Social Networks</h3>
                    {% if profile.facebook %}
                    <div class="social-network with-icon">
                        <img src="{{ asset('static/typicons.2.0/png-24px/social-facebook.png') }}" />
                        <a href="http://facebook.com/{{ profile.facebook }}">{{ profile.facebook }}</a>
                    </div>
					{% endif %}
					
					{% if profile.twitter %}
                    <div class="social-network with-icon">
                        <img src="{{ asset('static/typicons.2.0/png-24px/social-twitter.png') }}" />
                        <a href="https://twitter.com/{{ profile.twitter }}">{{ profile.twitter }}</a>
                    </div>
					{% endif %}
					
					{% if profile.linkedin %}
                    <div class="social-network with-icon">
                        <img src="{{ asset('static/typicons.2.0/png-24px/social-linkedin.png') }}" />
                        <a href="{{ profile.linkedin }}">LinkedIn Profile</a>
                    </div>
					{% endif %}
					
					{% if profile.skype %}
					<div class="social-network with-icon">
					    <img src="{{ asset('static/typicons.2.0/png-24px/social-skype.png') }}" />
					    <a href="skype:{{ profile.skype }}?call">{{ profile.skype }}</a>
					</div>
					{% endif %}
                    
                </div>
            </section>
            
            {% if is_granted('EDIT', profile) %}
			<a class="edit-link" href="{{ path('company_edit', {slug: profile.slug}) }}"><img src="{{ asset('static/typicons.2.0/png-24px/edit.png') }}" />Edit Profile</a>
			{% endif %}
        </div>
    </div>
</div>

{% if is_granted("ROLE_ADMIN") %}
<div class="row">
    <div class="span12">
        <h3>Administrators</h3>
        <ul>
            {% for user in profile.users %}
            <li>
                <a href="{{ path('user_show', {id: user.id}) }}">{{ user.name }}</a>
                (<a href="mailto:{{ user.email }}">{{ user.email }}</a>)
            
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endif %}
{# {% if app.user != profile %}#}
{# <div id="profileRqst">#}
{# 	{% include 'WanaworkUserBundle:EmployeeProfile:_requests-table.html.twig' with {#}
{# 					requests: cvRequests,#}
{# 					emptyMessage: 'You don\'t have any CV requests from this Employer',#}
{# 					hideCompanyColumn: true#}
{# 				} %}#}
{# </div>#}
{# {% endif %}#}

{% endblock %}

{% block stylesheets %}
{{ parent() }}
{% stylesheets filter='?yui_css' filter='cssrewrite'
	'@WanaworkUserBundle/Resources/public/css/employerProfile/profile.css'
	 %}
	<link rel="stylesheet" type="text/css" media="all" href="{{ asset(asset_url) }}" />
{% endstylesheets %}		
{% endblock %}

src/Wanawork/UserBundle/Resources/views/EmployerProfile/verification-pending.html.twig
{% extends "WanaworkUserBundle::base.html.twig" %}

{% block title %}Company Verification Pending{% endblock %}

{% block body %}
<div class="row">
    <div class="span12">
        <div class="empty-wrapper">
            <div class="message-content">
                <h1>Verification Pending</h1>
                <p>
                    We are currently reviewing your verification request and will be in touch shortly
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}