src/Wanawork/UserBundle/Entity/CvRequest.php
<?php
namespace Wanawork\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Wanawork\UserBundle\Exception\UserAndEmployerProfileMisMatchException;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * CV Request 
 * @author Ilya Biryukov <ilya@wanawork.ie>
 * @ORM\Entity(repositoryClass="Wanawork\UserBundle\Repository\CvRequestRepository")
 * @ORM\Table(
 *  uniqueConstraints={
 *      @ORM\UniqueConstraint(name="employer_ad", columns={"employerprofile_id", "ad_id"})
 *  }
 * )
 * @Assert\Callback(methods={"validate"})
 */
class CvRequest
{

    const AWAITING = 1;

    const GRANTED = 2;

    const DENIED = 3;
    
    static $statuses = array(
        'pending' => self::AWAITING,
        'approved' => self::GRANTED,
        'denied' => self::DENIED,
    );

    /**
     * Request ID
     * 
     * @var integer 
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * The user who requested access
     * 
     * @var \Wanawork\UserBundle\Entity\User 
     * 
     * @ORM\ManyToOne(targetEntity="User")
     * @Assert\NotNull()
     * @Assert\Type(type="\Wanawork\UserBundle\Entity\User", message="CV Request requires a valid user")
     */
    protected $user;

    /**
     * The employer profile which made the request
     * 
     * @var \Wanawork\UserBundle\Entity\EmployerProfile 
     * @ORM\ManyToOne(targetEntity="Wanawork\UserBundle\Entity\EmployerProfile", inversedBy="cvRequests")
     * @Assert\NotNull()
     * @Assert\Type(type="\Wanawork\UserBundle\Entity\EmployerProfile", message="CV Request requires a valid employer profile")
     */
    protected $employerProfile;

    /**
     * Ad to which request was submitted
     * 
     * @var Ad 
     * @ORM\ManyToOne(targetEntity="Ad", inversedBy="accessRequests")
     * @Assert\NotNull()
     * @Assert\Type(type="\Wanawork\UserBundle\Entity\Ad", message="CV Request requires a valid ad")
     */
    protected $ad;

    /**
     * Request status
     * 
     * @var integer 
     * @ORM\Column(type="integer")
     * @Assert\NotNull
     * @Assert\Choice(callback = "getStatuses")
     * 
     */
    protected $status;

    /**
     * When the request was submitted
     * 
     * @var \DateTime 
     * @ORM\Column(type="datetime")
     * 
     * @Assert\NotNull()
     * @Assert\Type(type="\DateTime", message="Creating date must be a valid date/time")
     */
    protected $createDate;

    /**
     * The date when a response was given
     * 
     * @var \DateTime 
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Type(type="\DateTime", message="Response date must be a valid date/time")
     */
    protected $responseDate;

    /**
     * The mail communication for this request
     * 
     * @var Wanawork\UserBundle\Entity\MailThread
     * @ORM\OneToOne(targetEntity="Wanawork\UserBundle\Entity\MailThread", mappedBy="cvRequest", cascade={"all"})
     */
    protected $mailThread;
    
    /**
     * Job for which this request is
     * @var Wanawork\UserBundle\Entity\JobSpec
     * @ORM\ManyToOne(targetEntity="Wanawork\UserBundle\Entity\JobSpec")
     * @Assert\Valid()
     */
    protected $job;
    
    /**
     * Message to use
     * @var string
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(max=2000, maxMessage="Your message cannot be longer that {{ limit }} characters")
     */
    protected $message;

    /**
     * 
     * @param User $user
     * @param Ad $ad
     * @param EmployerProfile $profile
     * @throws UserAndEmployerProfileMisMatchException
     */
    public function __construct(User $user = null, Ad $ad = null, EmployerProfile $profile = null, JobSpec $job = null, $message = null)
    {
        $this->employerProfile = $profile;
        $this->job = $job;
        $this->setUser($user);
        $this->setAd($ad);
        $this->createDate = new \DateTime();
        $this->responseDate = null;
        $this->status = self::AWAITING;
    }

    /**
     *
     * @return \Wanawork\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     *
     * @return \Wanawork\UserBundle\Entity\Ad
     */
    public function getAd()
    {
        return $this->ad;
    }

    public function setAd($ad)
    {
        $this->ad = $ad;
        
        if ($ad instanceof Ad) {
            $ad->addAccessRequest($this);
        }
    }

    /**
     * @return \DateTime
     */
    public function getCreateDate()
    {
        return $this->createDate;
    }

    /**
     * 
     * @return \DateTime
     */
    public function getResponseDate()
    {
        return $this->responseDate;
    }
    
    /**
     * Get the list of valid statuses
     * 
     * @return array
     */
    public function getStatuses()
    {
        return self::$statuses;
    }

    /**
     * @return number
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function getStatusName()
    {
        return array_search($this->getStatus(), self::$statuses);;
    }

    /**
     * Check if the access is granted
     * 
     * @return boolean
     */
    public function isGranted()
    {
        return $this->getStatus() === self::GRANTED;
    }

    public function isPending()
    {
        return $this->getStatus() === self::AWAITING;
    }

    public function isDenied()
    {
        return $this->getStatus() === self::DENIED;
    }

    public function setStatus($status)
    {
        if (! in_array($status, self::$statuses)) {
            throw new \InvalidArgumentException("Invalid Status Code Given: '$status'");
        }
        
        if ($status === self::GRANTED) {
            $this->createMailThread();
        }
        
        $this->status = $status;
        $this->responseDate = new \DateTime();
    }

    public function approve()
    {
        $this->setStatus(self::GRANTED);
    }

    public function deny()
    {
        $this->setStatus(self::DENIED);
    }

    /**
     *
     * @return \Wanawork\UserBundle\Entity\MailThread
     */
    public function getMailThread()
    {
        return $this->mailThread;
    }

    /**
     * @return \Wanawork\UserBundle\Entity\MailThread
     */
    public function createMailThread()
    {
        $thread = $this->getMailThread();
        
        if(!$thread) {
            $thread = $this->mailThread = new MailThread($this);
        }
        
        return $thread;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setUser($user)
    {
        $this->user = $user;
    }

    public function getJob()
    {
        return $this->job;
    }

    public function setJob($job)
    {
        $this->job = $job;
    }

    public function getEmployerProfile()
    {
        return $this->employerProfile;
    }

    public function setEmployerProfile($employerProfile)
    {
        $this->employerProfile = $employerProfile;
    }
    
    public function validate(ExecutionContextInterface $context)
    {
        if (!strlen($this->getMessage()) && !$this->getJob()) {
            $context->addViolation('Please provide either a message or select a job description');
        }
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($message)
    {
        $this->message = $message;
    }
    
    
}

src/Wanawork/UserBundle/Controller/CvRequestController.php
<?php
namespace Wanawork\UserBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Wanawork\UserBundle\Entity\CvRequest;
use Wanawork\UserBundle\Form\CvRequestType;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Wanawork\UserBundle\Entity\Ad;
use Wanawork\UserBundle\Entity\EmployerProfile;
use Wanawork\UserBundle\Entity\AbstractProfile;
use Wanawork\UserBundle\Entity\EmployeeProfile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * CvRequest controller.
 *
 * @Route("/cv_request")
 */
class CvRequestController extends Controller
{

    /**
     * Lists all CvRequest entities.
     *
     * @Route("/", name="cv_request")
     * @Method("GET")
     * @Template()
     * @Secure(roles={"ROLE_ADMIN"})
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('WanaworkUserBundle:CvRequest')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    
    /**
     * @Route("/profile/{id}/{status}", name="cv_requests_by_profile", 
     *  requirements={"id"="\d+", "status"="\w+"}
     * )
     * @Method("GET")
     * @Secure(roles={"ROLE_USER"})
     */
    public function listAction(AbstractProfile $profile, $status = null)
    {
        if ($status !== null && !array_key_exists($status, CvRequest::$statuses)) {
            throw $this->createNotFoundException();
        }
        $statusId = ($status === null) ? null : CvRequest::$statuses[$status];
        
        $security = $this->get('security.context');
        if (!$security->isGranted("EDIT", $profile)) {
            throw new AccessDeniedException();
        }
        
        $requests = $profile->getCvRequests($statusId);
        $template = $profile instanceof EmployerProfile ? 'employer' : 'candidate';
        
        $updateStatusForms = array();
        $deleteForms = array();
        foreach ($requests as $request) {
            $updateStatusForms[$request->getId()] = $this->createUpdateStatusForm($request->getId())->createView();
            $deleteForms[$request->getId()] = $this->createDeleteForm($request->getId())->createView();
        }
        
        $aclManager = $this->get('wanawork.acl_service');
        $aclManager->preloadAcls($requests);
        
        
        $viewOptions = array(
        	'requests' => $requests,
            'status' => $status,
            'update_status_forms' => $updateStatusForms,
            'delete_forms' => $deleteForms,
        );
        
        return $this->render("WanaworkUserBundle:CvRequest:list-{$template}.html.twig", $viewOptions);
    }


    /**
     * Displays a form to create a new CvRequest entity.
     * 
     * @Route("/new/ad/{id}", name="cv_request_new", requirements={"id"="\d+"})
     * @ParamConverter("ad", class="WanaworkUserBundle:Ad")
     */
    public function newAction(Ad $ad)
    {
        $user = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $request = $this->getRequest();
        
        // Check login ?
        if (!$user) {
            return $this->render('WanaworkUserBundle:CvRequest:login-required.html.twig');                
        }
        
        // No company profiles?
        if (sizeof($user->getEmployerProfiles()) === 0) {
            return $this->render('WanaworkUserBundle:CvRequest:company-profile-required.html.twig');
        }
        
        // Default profile is not employer profile?
        if(!$user->getDefaultProfile() instanceof EmployerProfile) {
            if (sizeof($user->getEmployerProfiles()) === 1) {
                $user->setDefaultProfile($user->getEmployerProfiles()->first());
                $em->flush();
                
                // refresh the page
                return $this->redirect($this->generateUrl('cv_request_new', array(
                	'id' => $ad->getId(),
                )));
                
            } else {
                return $this->render('WanaworkUserBundle:CvRequest:select-profile.html.twig');
            }
        }
        
        if ($user->getDefaultProfile()->getRemainingCVRequests() === 0) {
            return $this->render('WanaworkUserBundle:CvRequest:no-cv-request-left.html.twig');
        }
        
        if($user->getDefaultProfile()->getCvRequests()->get($ad->getId())) {
            return $this->render('WanaworkUserBundle:CvRequest:request-already-exists.html.twig', array(
            	'request' => $user->getDefaultProfile()->getCvRequests()->get($ad->getId())
            ));            
        }
        
        if ($ad->isExpired() || !$ad->isPublished()) {
            return $this->render('WanaworkUserBundle:CvRequest:_ad-expired.html.twig');
        }
        
        $cvRequest = new CvRequest();
        $cvRequest->setEmployerProfile($user->getDefaultProfile());
        $cvRequest->setAd($ad);
        $cvRequest->setUser($user);
        
        $form = $this->createForm(new CvRequestType($user->getDefaultProfile()), $cvRequest);
        
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $cvService = $this->get('wanawork.cv_service');
                $cvService->createCvRequest($cvRequest);

                $url = $this->generateUrl('wanawork_main_search');
                if ($request->query->get('redirect')) {
                    $url = $request->query->get('redirect') . '#' . 'ad-box-' . $ad->getId();
                }
                return $this->redirect($url, 201);
            }
        }
        
        $viewOptions = array(
        	'form' => $form->createView(),
            'ad' => $ad,
        );
        return $this->render('WanaworkUserBundle:CvRequest:new.html.twig', $viewOptions);
    }

    /**
     * Finds and displays a CvRequest entity.
     *
     * @Route("/{id}", name="cv_request_show")
     * @Method("GET")
     * @Template()
     * @Secure(roles={"ROLE_ADMIN"})
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('WanaworkUserBundle:CvRequest')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find CvRequest entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing CvRequest entity.
     *
     * @Route("/{id}/edit", name="cv_request_edit")
     * @Method("GET")
     * @Template()
     * @Secure(roles={"ROLE_ADMIN"})
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('WanaworkUserBundle:CvRequest')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find CvRequest entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a CvRequest entity.
    *
    * @param CvRequest $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(CvRequest $entity)
    {
        $form = $this->createForm(new CvRequestType($entity->getEmployerProfile()), $entity, array(
            'action' => $this->generateUrl('cv_request_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing CvRequest entity.
     *
     * @Route("/{id}", name="cv_request_update")
     * @Method("PUT")
     * @Template("WanaworkUserBundle:CvRequest:edit.html.twig")
     * @Secure(roles={"ROLE_ADMIN"})
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('WanaworkUserBundle:CvRequest')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find CvRequest entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('cv_request_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a CvRequest entity.
     *
     * @Route("/{id}.{format}", name="cv_request_delete",
     *  defaults={"format"="html"}, requirements={"id"="\d+", "format"="html|json"})
     * @Method("DELETE")
     * @Secure(roles={"ROLE_USER"})
     */
    public function deleteAction(CvRequest $cvRequest)
    {
        $security = $this->get('security.context');
        if (!$security->isGranted("DELETE", $cvRequest)) {
            throw new AccessDeniedException();
        }
        
        $format = $this->getRequest()->getRequestFormat();
        
        $form = $this->createDeleteForm($cvRequest->getId());

src/Wanawork/UserBundle/Resources/views/CvRequest/_ad-expired.html.twig
{% extends '::base.html.twig' %}

{% block body %}

<div class="row">
    <div class="span12 heading">
        <h1>CV Access Request</h1>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="empty-wrapper">
            <div class="message-content">
                <h3>The Ad has expired</h3>
                <p>
                    You cannot request access to full CV if the ad is expired
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/Wanawork/UserBundle/Resources/views/CvRequest/company-profile-required.html.twig
{% extends '::base.html.twig' %}

{% block body %}

<div class="row">
    <div class="span12 heading">
        <h1>CV Access Request</h1>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="empty-wrapper">
            <div class="message-content">
                <h3>Company Profile Required</h3>
                <p>
                    In order to request access to CVs, you need:
                    <ol>
                        <li>
                            To be logged in
                        </li>
                        <li>
                            To have a company account created
                        </li>
                    </ol>
                </p>
                
                <hr class="divider" />
                
                <a href="{{ path("company_new") }}" class="btn btn-main">Create Company Profile</a>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
{% stylesheets filter='?yui_css' filter='cssrewrite'
    'bundles/wanaworkuser/css/cvRequest/login-required.css'
	 %}
	<link rel="stylesheet" type="text/css" media="all" href="{{ asset(asset_url) }}" />
{% endstylesheets %}
{% endblock %}

src/Wanawork/UserBundle/Resources/views/CvRequest/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>CvRequest edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('cv-request') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Wanawork/UserBundle/Resources/views/CvRequest/list-candidate.html.twig
{% extends app.request.isXmlHttpRequest ? "::blank.html.twig" : "WanaworkUserBundle::base.html.twig" %}

{% block title %}CV Shortlist Requests{% endblock %}

{% block body %}
<div class="row">
    <div class="span12 heading">
        <h1>CV Shortlist Requests</h1>
        <h2>Below is a list of requests you received from employers who wish to access your full CV</h2>
    </div>
</div>

<div class="row">
    <div class="span12">
        
        <div class="cv-requests">
        
            {% if requests | length > 0 or status is not null %}
		    <div class="filter-buttons">
			    <span><i class="icon icon-info-sign"></i>&nbsp;Show me:</span>   
				<a class="all {{ status is null ? 'active' : '' }}" href="{{ path('my_cv_requests') }}">All</a>
				<a class="pending {{ status=='pending' ? 'active' : '' }}" 
				   href="{{ path('my_cv_requests', {status: 'pending'}) }}">Pending</a>
				<a class="approved {{ status=='approved' ? 'active' : '' }}" 
				   href="{{ path('my_cv_requests', {status: 'approved'}) }}">Approved</a>
				<a class="denied {{ status=='denied' ? 'active' : '' }}" 
				   href="{{ path('my_cv_requests', {status: 'denied'}) }}">Denied</a>
			</div>
	        <div class="status-toopltip">
	            <b>Pending</b>
	            <p>You havn't yet replied to employer's request.</p>
	            <b>Approved</b>
	            <p>You approved employer's request. The employer can now view your full CV and communicate with you in chat</p>
	            <b>Denied</b>
	            <p>Your denied employer's request. Employer will not be able to access your full CV</p>
	        </div>
			{% endif %}
        
        {% for request in requests %}
	        
            {% if request.isGranted %}
				{% set statusClass = 'success' %}
				{% set replyTitle = "Approved on " ~ request.responseDate.format(date_format) %}
			{% elseif request.isDenied %}
				{% set statusClass = 'important' %}
				{% set replyTitle = "Denied on " ~ request.responseDate.format(date_format) %}
			{% elseif request.isPending %}
				{% set statusClass = 'info' %}
				{% set replyTitle = '' %}
			{% endif %}
					
	        <div class="cv-request">
	            <div class="line clearfix">
	                <div class="description">Requested Ad</div>
	                <div class="text">
	                    <a href="{{ path('ad_show', {slug: request.ad.slug}) }}">{{ request.ad.headline }}</a>
	                </div>
	            </div>
	            
	            <div class="line clearfix">
	                <div class="description">Company</div>
	                <div class="text">
	                    <a href="{{ path('company_show', {slug: request.employerProfile.slug}) }}">{{ request.employerProfile.companyName }}</a>
						{% if request.employerProfile.isVerified %}
						<sup><span class="label label-info">Verified</span></sup>
						{% endif %}
	                </div>
	            </div>
	            
	            <div class="line clearfix">
	                <div class="description">Requested Date</div>
	                <div class="text">
	                    <span class="timeago" title="{{ request.createDate.format('c') }}">
							{{ request.createDate.format(date_format) }}
						</span>
	                </div>
	            </div>
	            
	            <div class="line clearfix">
	                <div class="description">Status</div>
	                <div class="text">
	                    <span title="{{ replyTitle }}" class="label label-{{ statusClass }} {{ replyTitle ? '' : '' }}">
							{{ request.statusName | capitalize }}
						</span>
						
						{% if request.isGranted or request.isDenied %}
						<br />
						<span class="timeago" title="{{ request.responseDate.format('c') }}">
							{{ request.responseDate.format(date_format) }}
						</span>
						{% endif %}
	                </div>
	            </div>
	            
	            {% if request.message %}
	            <div class="line clearfix">
	                <div class="description">Message to candidate</div>
	                <div class="text">
					    {{ request.message }}
	                </div>
	            </div>
	            {% endif %}
	            
	            {% if request.job %}
	            <div class="line clearfix">
	                <div class="description">Offered Position</div>
	                <div class="text">
					    <a href="{{ path('jobs_show', {id: request.job.id, title: clean_url(request.job.title)}) }}">{{ request.job.title }}</a>
	                </div>
	            </div>
	            {% endif %}
	            
	            <div class="actions">
			  	{% if request.isGranted and request.mailThread and is_granted('CREATE', request.mailThread) %}
			  		<a href="{{ path('mailbox_index', {id: request.mailThread.id}) }}">
			  			<i class="icon icon-envelope"></i>Send a Message
			  		</a>
			  	{% elseif request.mailThread and is_granted("VIEW", request.mailThread) %}
			  		<a href="{{ path('mailbox_index', {id: request.mailThread.id}) }}">
			  			<i class="icon icon-envelope"></i>
			  			View Messages
			  		</a>
			  	{% endif %}
			  	
			  	{% if request.isPending and is_granted('EDIT', request) and request.ad.cv %}
			  	    <form class="update-status-form" action="{{ path('cv_request_set_status', {id: request.id}) }}" method="POST">
			            {{ form_widget(update_status_forms[request.id]) }}
				  	    {% if not request.isGranted %}
				    	<button class="btn btn-success approve"
				    	   data-status="{{ constant('Wanawork\\UserBundle\\Entity\\CvRequest::GRANTED') }}">
				    	   <i class="icon icon-ok icon-white"></i>&nbsp;Approve
				        </button>
				        {% endif %}
				    
				        {% if not request.isDenied %}
				    	<button class="btn btn-danger deny" 
				    	   data-status="{{ constant('Wanawork\\UserBundle\\Entity\\CvRequest::DENIED') }}">
				    		<i class="icon icon-ban-circle icon-white"></i>&nbsp;Deny
				    	</button>
				        {% endif %}
				    </form>
				{% elseif not request.ad.cv %}
				
				<a href="{{ path('ad_edit', {slug: request.ad.slug}) }}" class="btn" style="margin-top: 10px;">Upload CV to respond</a>
				<p>Your advert is missing a CV. Before you can grant/deny this employer access, you need to upload a CV first.</p>
			    {% endif %}
			    </div> 
	            
	        </div>
        
        {% else %}
            <div class="empty-wrapper">
                <div class="message-content">
				{% if emptyMessage is defined %}
					{{ emptyMessage }}
				{% else %}
					You don't have any {{ status }} cv requests yet
				{% endif %}
				</div>
		    </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts filter='?yui_js' '@WanaworkUserBundle/Resources/public/js/cvRequest/list.js' %}
    <script src="{{ asset(asset_url) }}"></script>
	{% endjavascripts %}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{% stylesheets '@WanaworkUserBundle/Resources/public/css/cvRequest/list.css' filter='?yui_css' filter='cssrewrite' %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ asset(asset_url) }}" />
	{% endstylesheets %}
{% endblock %}

src/Wanawork/UserBundle/Resources/views/CvRequest/no-cv-request-left.html.twig
{% extends '::base.html.twig' %}

{% block body %}

<div class="row">
    <div class="span12 heading">
        <h1>CV Access Request</h1>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="empty-wrapper">
            <div class="message-content">
                <h3>No More CV Requests Left</h3>
                <p>
                    You have no more CV Requests left for today.
                    <br />
                    Please <a href="">upgrade your package</a> or come back tomorrow
                </p>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/Wanawork/UserBundle/Resources/views/CvRequest/request-already-exists.html.twig
{% extends '::base.html.twig' %}

{% block title %}CV Request Pending{% endblock %}

{% block body %}

<div class="row">
    <div class="span12 heading">
        <h1>CV Access Request</h1>
    </div>
</div>

<div class="row">
    <div class="span12">
        <div class="empty-wrapper">
            <div class="message-content">
                <h3>Request Already Exists</h3>
                <p>
                    You already submitted a request for the ad ({{ request.ad.headline }}), 
                    <abbr class="last-message-time timeago" title="{{ request.createDate.format('c') }}">
                    {{request.createDate.format(date_format) }}</abbr>. <br />
                    Request Status: {{ request.statusName }}
                </p>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}